### ISSUE TITLE
Point cloud surface reconstruction of large scenes

### ISSUE THREAD

**Issue by qixuema** [microsoft/DualOctreeGNN#1]
Hi @wang-ps,

Thanks for sharing the fantastic work!

We have recently been working on point cloud surface reconstruction of large scenes. I want to ask if DualOctreeGNN can be used for surface reconstruction of point clouds for large scenes like this.

![L7](https://user-images.githubusercontent.com/58554118/181504801-188959aa-21a6-4cf9-b96b-371044a12603.png)

Thank you for your response in advance!

**Comment by wang-ps** [comment]
Yes, it is definitely possible. 

I think you can set the depth of the octree as 10 or 11, which corresponds to a spatial resolution of 1024^3 or 2014^3, and train the network on appropriate datasets. 

Moreover, currently, the marching cube algorithm for extracting surfaces is executed on the CPU, which is the bottleneck of the whole pipeline. An improved implementation on adaptive octrees may greatly speed up the mesh extraction.

**Comment by qixuema** [comment]
Thank you very much for your reply!

**Comment by qixuema** [comment]
Hi, Dr. Wang(@wang-ps ),

I recently used the [gibson_tiny  dataset](http://gibsonenv.stanford.edu/) for unsupervised training. And when I test it, the generated result appears like an envelope. Do you know the reason for this situation?

The results of the reconstruction are as follows:

![bb045490d98543fa1a96c654feade4e](https://user-images.githubusercontent.com/58554118/182528991-ed5530df-85eb-4aeb-bbc4-96b183f68561.png)

And the ground truth is:

![3fb9ab40f57081babf941f0918979a3](https://user-images.githubusercontent.com/58554118/182529114-f1bc0023-0e74-4f39-ac91-d43886ba2e40.png)

The envelope looks like this:

![0d15a7aec49a7bda64db7adff375dfc](https://user-images.githubusercontent.com/58554118/182529208-b31db3a5-c61c-415e-bf9c-c408da0e3bf6.png)

![cab6ca05c97ff3fc0e613d3bba11950](https://user-images.githubusercontent.com/58554118/182529609-0f5e3073-b74c-4fc7-9a68-dec4cad3a4cd.png)

**Comment by wang-ps** [comment]
I suggest rescaling the object to 0.8 or 0.7 of the bounding box, training the network for a longer time, or with more training samples.

**Comment by qixuema** [comment]
Thank you very much for your reply. 

Indeed the number of samples is too small. But I don't have a larger data set at the moment.

I will try to change the scale to 0.8 to see if there is any effect.
