### ISSUE TITLE
Scale of sdf?

### ISSUE THREAD

**Issue by XinYu-Andy** [microsoft/DualOctreeGNN#2]
Hi,

Thanks for your great work! I noticed that the paper said the mesh is processed to the watertight and scaled into the bounding box [-0.5,0.5]^3. I am wondering what the scale is of the computed SDF? It seems that the mesh2sdf.compute() receives a mesh in the bounding box [-1,1]^3. 
So, does it mean the sdf is calculated in this range? i.e., the output (128,128,128) tensor should be SDF values of grid-coordinates in [-1,1]^3?

**Comment by XinYu-Andy** [comment]
Also, I am curious about why we need scale the mesh into [-0.5,0.5], since i noticed that when you sample the pointcloud from the mesh, the points are then scaled back into [-1,1]?

**Comment by wang-ps** [comment]
In my initial experiments, I did scale the mesh into [-1, 1]. And the SDF is calculated on such a scale.

 And since I reuse the evaluation code and results of ConvONet, ConvONet scales the mesh into [-0.5, 0.5], and I also scale the input point cloud and output mesh into [-0.5, 0.5] while keeping SDF fixed.

When training the network, the point cloud in [-0.5, 0.5] is rescale to [-1, 1] ( [ref link](https://github.com/microsoft/DualOctreeGNN/blob/main/datasets/shapenet.py#L31) )

**Comment by XinYu-Andy** [comment]
Thanks for your reply!

**Comment by XinYu-Andy** [comment]
Hi,

Sorry for bother, I have another question.
I am wondering whether I only need to change the "size=128" to "size=256" in the "tools/shapenet.py" for generating SDF with voxel size=256 and the corresponding "point cloud", "points", and "occupancy"? 
Are there any other code I need to modify?

Thanks!

**Comment by XinYu-Andy** [comment]
Because I find it will not work when I train an implicit autoencoder model with SDF resolution=256, while it works well with SDF resolution=128.

**Comment by XinYu-Andy** [comment]
> Because I find it will not work when I train an implicit autoencoder model with SDF resolution=256, while it works well with SDF resolution=128.

I suspect there are some inconsistencies in the function "def sample_sdf()".

**Comment by wang-ps** [comment]
The code can work with depth=8 since I have tried it in my personal experiments before. 
I suggest understanding the code and checking all the places related to `depth`, including the code and the `*.yaml` configuration files.

**Comment by XinYu-Andy** [comment]
Thanks for you reply.

In fact, I am not concerning about `depth`, but the [`size`](https://github.com/microsoft/DualOctreeGNN/blob/29eed84653d4f0c1681c8227714cf84e76c31abe/tools/shapenet.py#L32) (i.e., resolution of SDF).
In fact, I have checked the code after I opened this issue, and find that it seems some codes should be modified, e.g., [this line](https://github.com/microsoft/DualOctreeGNN/blob/29eed84653d4f0c1681c8227714cf84e76c31abe/tools/shapenet.py#L227) and [this line](https://github.com/microsoft/DualOctreeGNN/blob/29eed84653d4f0c1681c8227714cf84e76c31abe/tools/shapenet.py#L255).
The `(xyz<127)` should be changed into `(xyz<size-1)`, while the `(xyzs/64-1)` should be changed into `(2*xyzs/size-1)`.

**Comment by wang-ps** [comment]
Good job! Yes, you are right!

**Comment by XinYu-Andy** [comment]
Thanks for your patient, I am new in this field, I still have another trivial question :{
Is there a way to directlt compute the SDF value near the surface? I understand that in your codebase, you firstly compute a `SDF voxel`, then do interpolation to get SDF value for query points near the surface.
This may poses several issues:
1. SDF might be not accurate.
2. Pre-computing sdf voxel is costly or useless since many of them will be not used.
I am seeking a way to compute sdf for irregular points efficiently.

**Comment by XinYu-Andy** [comment]
> Thanks for your patient, I am new in this field, I still have another trivial question :{ Is there a way to directlt compute the SDF value near the surface? I understand that in your codebase, you firstly compute a `SDF voxel`, then do interpolation to get SDF value for query points near the surface. This may poses several issues:
> 
> 1. SDF might be not accurate.
> 2. Pre-computing sdf voxel is costly or useless since many of them will be not used.
>    I am seeking a way to compute sdf for irregular points efficiently.

Also, why do we set the [mesh scale](https://github.com/microsoft/DualOctreeGNN/blob/29eed84653d4f0c1681c8227714cf84e76c31abe/tools/shapenet.py#L122) to 0.8? I do think if we set it more close to 1 (e.g., 0.9), the produced sdf could recounstruct the mesh better because the sampled points are uniform grids in [-1,1]^3. What are the considerations when setting this value (i.e., mesh_scale)?

**Comment by wang-ps** [comment]
Yes, it is OK to set it to 0.9. 
The value 0.8 is relatively conservative. Since the dataset construction process is time-consuming, I did not try it in my experiment after I first constructed the dataset with the mesh scale factor as 0.8.

> Also, why do we set the [mesh scale](https://github.com/microsoft/DualOctreeGNN/blob/29eed84653d4f0c1681c8227714cf84e76c31abe/tools/shapenet.py#L122) to 0.8? I do think if we set it more close to 1 (e.g., 0.9), the produced sdf could recounstruct the mesh better because the sampled points are uniform grids in [-1,1]^3. What are the considerations when setting this value (i.e., mesh_scale)?

**Comment by wang-ps** [comment]
> SDF might be not accurate

Yes, there do exist approximation errors with a resolution of 128^3 (less than 1% of the bounding box) .

> Pre-computing sdf voxel is costly or useless since many of them will be not used. I am seeking a way to compute sdf for irregular points efficiently.

The OpenVDB library contains such functions. However, I am not familiar with OpenVDB either and I could not provide more information about it.

**Comment by XinYu-Andy** [comment]
Thank you very much!
