### ISSUE TITLE
Overfit on one shape

### ISSUE THREAD

**Issue by csyhping** [microsoft/DualOctreeGNN#5]
Hi @wang-ps , thanks for your amazing work. May I ask if it is possible to overfit on one shape? I tried but I could not get the correct result (on autoencoder experiment), the extracted mesh is not even similar to the input, just several pieces or blocks. I set the training set with only one shape and tested it with the same shape.

Thanks.

**Comment by wang-ps** [comment]
Perhaps you should increase the training time.
Theoretically, if the network can well fit the whole ShapeNet, it is easy for it to fit a single shape.

**Comment by csyhping** [comment]
@wang-ps Thanks for your reply. This is because of the training time, and according to my test, it needs far more than 300 epochs, which was out of my expectations at the first time. 

Yes, it should be ok to overfit on one shape, just like other implicit representation networks. 

Many thanks again for your excellent work and reply! Have a nice day!
